on:

  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: docker build and test
#      id: hello
#      uses: actions/hello-world-docker-action@v1
      uses: jimthompson5802/ga_sandbox/docker/custom_build_test@v0.0.6
#      with:
#        who-to-greet: 'Say hi to Jim'
#    # Use the output from the `hello` step
#    - name: Get the output time
#      run: echo "The time was ${{ steps.hello.outputs.time }}"